### ISSUE TITLE
Stuff to improve on

### ISSUE THREAD

**Issue by MiniDigger** [The-SourceCode/Bukkit_Coding_Tutorial#1]
Hey there!
nice to see that you want to help ppl to learn to code!
There seem to be some things _you_ can improve on:

1. upload the full projects here, not only weird files without extentions
2. don't use illegally distribute spigot jars, only legal way to get spigot is via [buildtools](https://www.spigotmc.org/wiki/buildtools/)
3. don't use bungees chatcolor if you don't need to
4. don't log that your plugin was enabled, bukkit does that
5. don't log multi line via \n, breaks formatting
6. use @Override if you override methods from a superclass (to avoid typos ;))
7. explain what deprecated means and why it is bad to use those methods
8. use name() on enums to convert it to a readable string
9. encourage [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) (you copy pasted the event listener for block place)
10. you can access server stuff using the Bukkit class
11. don't extend CommandExecute if you want to make commands....
12. you can save locations directly, no need to save every coordinate

advanced stuff:
1. suggest other IDEs
2. suggest a proper build system

keep up the great work!

**Comment by The-SourceCode** [comment]
Thank you.

1. i only upload the files because there is no need to upload the whole project. They are learning the code, which can be seen from these very files.
2. I just use that because most times it is much easier for people and have had no issues with that site. People can do it however they see fit but I think most people want the easiest way.
3. Most times that is from an improper import. 
4. Some people like to see a nicely colored message, or a custom message when they launch their plugin. 
5. Using \n in log should not work anyway from what I remember. If it does I probably just used it for speed purposes.
6. Not sure what methods other than onEnable/disable I have used that would call for an override
7. Copy that
8. Copy that
9. Copy that
10. True, but most times I just use the main class instance because I need to grab stuff from the main class.
11. Copy that
12. I usually save every cord because I do not want all the extra crap that goes along with it.
